target 'ISO639' do
  platform :ios, 12.0
  use_frameworks!

  pod "Bow", "~> 0.8.0"
  pod "BowEffects", "~> 0.8.0"
  pod "BowRx", "~> 0.8.0"
  pod "BowOptics", "~> 0.8.0"
  pod "BowGeneric", "~> 0.8.0"
  pod "BowRecursionSchemes", "~> 0.8.0"
  pod "BowFree", "~> 0.8.0"
end
