name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nef
      run: brew install nef
    - name: Create ISO639.playgroundbook
      run: nef ipad --name ISO639 --package Package.swift --output PlaygroundBook
    - name: Upload ISO639.playgroundbook
      uses: actions/upload-artifact@v1
      with:
        name: PlaygroundBook
        path: PlaygroundBook/ISO639.playgroundbook
